language: ruby
cache: bundler
rvm:
- 2.5.7
- 2.6.5
addons:
  postgresql: '12'
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
before_install:
# setting up postgres 12 is quite a pain, see:
# https://travis-ci.community/t/test-against-postgres-12/6768/8
  - sudo cp /etc/postgresql/10/main/pg_hba.conf /etc/postgresql/12/main/pg_hba.conf
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
  - sudo pg_ctlcluster 12 main restart
install: bin/setup
after_script: bin/ci/after_script
